-- ! AUTO-GENERATED — source: each modules/<dir>/config.json (dir name = modules.name). Regenerate: pnpm supabase:merge-sql

alter table public.modules add column if not exists name text;
alter table public.modules add column if not exists description text;
alter table public.modules add column if not exists category text;
alter table public.modules add column if not exists version text;
alter table public.modules add column if not exists enabled boolean not null default false;
alter table public.modules add column if not exists installed boolean not null default false;
alter table public.modules add column if not exists created_at timestamptz not null default now();
alter table public.modules add column if not exists updated_at timestamptz not null default now();

-- One row per directory under modules/ that has config.json; name = folder name (generated by generate-seeder.mjs)
delete from public.modules
where name not in ('nuc_activity', 'nuc_admin', 'nuc_animations', 'nuc_api', 'nuc_auth', 'nuc_breadcrumb', 'nuc_charts', 'nuc_colors', 'nuc_dark_mode', 'nuc_database', 'nuc_datatable', 'nuc_dialog', 'nuc_dock', 'nuc_documentation', 'nuc_documents', 'nuc_entities', 'nuc_entities_structural', 'nuc_fields', 'nuc_files', 'nuc_friendship', 'nuc_globals', 'nuc_languages', 'nuc_loading', 'nuc_media', 'nuc_modules', 'nuc_navigation', 'nuc_openapi', 'nuc_overrides', 'nuc_pagebuilder', 'nuc_pages', 'nuc_pricings', 'nuc_screen_loader', 'nuc_sections', 'nuc_settings', 'nuc_share', 'nuc_socials', 'nuc_stores', 'nuc_templates', 'nuc_terminal', 'nuc_tests', 'nuc_tooltip', 'nuc_users');

insert into public.modules (
  name, description, category, version, enabled, installed, created_at, updated_at
)
values
  ('nuc_activity', 'Module that contains Nucleify''s activity functions.', 'core', '0.3.0', true, true, now(), now()),
  ('nuc_admin', 'Module that contains admin functions.', 'core', '0.2.0', true, true, now(), now()),
  ('nuc_animations', 'Module that contains animation functions.', 'core', '0.3.2', true, true, now(), now()),
  ('nuc_api', 'Module that contains API functions.', 'core', '0.2.0', true, true, now(), now()),
  ('nuc_auth', 'Module that contains auth functions.', 'core', '0.5.0', true, true, now(), now()),
  ('nuc_breadcrumb', 'Module that contains breadcrumb functionality.', 'core', '0.1.0', true, true, now(), now()),
  ('nuc_charts', 'Module that contains chart functions.', 'core', '0.2.5', true, true, now(), now()),
  ('nuc_colors', 'Module that contains color functions.', 'core', '1.2.0', true, true, now(), now()),
  ('nuc_dark_mode', 'Module that contains dark mode functions.', 'core', '0.1.1', true, true, now(), now()),
  ('nuc_database', 'Module that manages database seeding with auto-discovery.', 'core', '0.1.2', true, true, now(), now()),
  ('nuc_datatable', 'Module that contains datatable functions.', 'core', '0.3.3', true, true, now(), now()),
  ('nuc_dialog', 'Module that contains dialog functionality.', 'core', '0.2.3', true, true, now(), now()),
  ('nuc_dock', 'Module that contains dock functionality.', 'core', '0.5.4', true, true, now(), now()),
  ('nuc_documentation', 'Module that contains documentation functions.', 'core', '1.0.0', true, true, now(), now()),
  ('nuc_documents', 'Module that contains convert document functions.', 'core', '0.0.1', true, true, now(), now()),
  ('nuc_entities', 'Module that contains entity functions.', 'core', '0.8.0', true, true, now(), now()),
  ('nuc_entities_structural', 'Module that contains structural entity functions.', 'core', '0.5.0', true, true, now(), now()),
  ('nuc_fields', 'Module that contains field functions.', 'core', '0.2.2', true, true, now(), now()),
  ('nuc_files', 'Module that contains file functions.', 'core', '0.3.0', true, true, now(), now()),
  ('nuc_friendship', 'Module that contains friendship functions.', 'core', '0.4.0', true, true, now(), now()),
  ('nuc_globals', 'Module that contains global functions, constants, etc.', 'core', '0.3.9', true, true, now(), now()),
  ('nuc_languages', 'Module that contains i18n functions.', 'core', '0.7.0', true, true, now(), now()),
  ('nuc_loading', 'Module that contains loading functions.', 'core', '0.0.3', true, true, now(), now()),
  ('nuc_media', 'Module that contains media functions.', 'core', '0.0.4', true, true, now(), now()),
  ('nuc_modules', 'Module that manages the modules of the application.', 'core', '0.9.0', true, true, now(), now()),
  ('nuc_navigation', 'Module that contains navigation functions.', 'core', '0.0.4', true, true, now(), now()),
  ('nuc_openapi', 'Module that contains OpenAPI 3.0 specification generation', 'api', '0.0.2', true, true, now(), now()),
  ('nuc_overrides', 'Module for overriding files for Nucleify', 'other', '0.1.0', true, true, now(), now()),
  ('nuc_pagebuilder', 'Module that provides elementor-like page builder with database persistence.', 'core', '0.4.0', true, true, now(), now()),
  ('nuc_pages', 'Module that contains page functions.', 'core', '0.8.1', true, true, now(), now()),
  ('nuc_pricings', 'Module for pricing sections and payment links.', 'core', '0.4.4', true, true, now(), now()),
  ('nuc_screen_loader', 'Module that contains screen loader functions.', 'core', '0.0.6', true, true, now(), now()),
  ('nuc_sections', 'Module that contains section functions.', 'core', '1.0.0', true, true, now(), now()),
  ('nuc_settings', 'Module that contains settings functions.', 'core', '0.4.5', true, true, now(), now()),
  ('nuc_share', 'Module that contains entity sharing functions.', 'core', '0.5.0', true, true, now(), now()),
  ('nuc_socials', 'Module that displays social media links.', 'social', '0.0.1', true, true, now(), now()),
  ('nuc_stores', 'Module that contains store functions.', 'core', '0.1.3', true, true, now(), now()),
  ('nuc_templates', 'Module that contains template functions.', 'core', '0.7.0', true, true, now(), now()),
  ('nuc_terminal', 'Module that contains terminal functions.', 'core', '0.3.0', true, true, now(), now()),
  ('nuc_tests', 'Module that contains testing infrastructure, utilities and helpers for Nucleify''s tests.', 'core', '0.2.1', true, true, now(), now()),
  ('nuc_tooltip', 'Module that contains tooltip functions.', 'core', '0.1.0', true, true, now(), now()),
  ('nuc_users', 'Module that contains user domain logic and user settings.', 'core', '0.4.1', true, true, now(), now())
on conflict (name) do update
set
  description = excluded.description,
  category = excluded.category,
  version = excluded.version,
  enabled = excluded.enabled,
  installed = excluded.installed,
  updated_at = now();
