#!/usr/bin/env node

import { dirname, join } from 'node:path'
import { fileURLToPath } from 'node:url'

/**
 * Scans every subdirectory of `modules` for `config.json` and rewrites the nuc_modules SQL seeder.
 * Invoked from merge-module-supabase-sql.sh before merging seeders.
 */
import { readdirSync, readFileSync, writeFileSync } from 'node:fs'

const __dirname = dirname(fileURLToPath(import.meta.url))
const repoRoot = join(__dirname, '../../..')
const modulesRoot = join(repoRoot, 'modules')
const outFile = join(
  repoRoot,
  'modules/nuc_modules/supabase/seeders/20260501000000_nuc_modules_seeder.sql'
)

/** @param {unknown} s */
function sqlString(s) {
  if (s == null) return "''"
  return `'${String(s).replace(/'/g, "''")}'`
}

/** @param {unknown} v @param {boolean} defaultVal */
function sqlBool(v, defaultVal) {
  if (v === undefined || v === null) return defaultVal ? 'true' : 'false'
  return v ? 'true' : 'false'
}

/** @typedef {{ name: string, description: string, category: string, version: string, enabled: boolean, installed: boolean }} Row */

/** @type {Row[]} */
const rows = []
for (const entry of readdirSync(modulesRoot, { withFileTypes: true })) {
  if (!entry.isDirectory()) continue
  const folderName = entry.name
  const dir = join(modulesRoot, folderName)
  const cfgPath = join(dir, 'config.json')
  let cfg
  try {
    const raw = readFileSync(cfgPath, 'utf8')
    cfg = JSON.parse(raw)
  } catch {
    continue
  }
  if (!cfg || typeof cfg !== 'object') continue

  if (typeof cfg.name === 'string' && cfg.name !== folderName) {
    process.stderr.write(
      `generate-seeder: warning ${folderName}: config "name" is "${cfg.name}"; using directory name as canonical key\n`
    )
  }

  rows.push({
    name: folderName,
    description: typeof cfg.description === 'string' ? cfg.description : '',
    category: typeof cfg.category === 'string' ? cfg.category : 'other',
    version: typeof cfg.version === 'string' ? cfg.version : '0.0.0',
    enabled: cfg.enabled !== false,
    installed: cfg.installed !== false,
  })
}

rows.sort((a, b) => a.name.localeCompare(b.name))

const preamble = `alter table public.modules add column if not exists name text;
alter table public.modules add column if not exists description text;
alter table public.modules add column if not exists category text;
alter table public.modules add column if not exists version text;
alter table public.modules add column if not exists enabled boolean not null default false;
alter table public.modules add column if not exists installed boolean not null default false;
alter table public.modules add column if not exists created_at timestamptz not null default now();
alter table public.modules add column if not exists updated_at timestamptz not null default now();

`

const banner =
  '-- One row per directory under modules/ that has config.json; name = folder name (generated by generate-seeder.mjs)\n'

let body
if (rows.length === 0) {
  body = `${banner}-- no modules with config.json found\nselect 1 where false;\n`
} else {
  const nameList = rows.map((r) => sqlString(r.name)).join(', ')
  const purge = `delete from public.modules
where name not in (${nameList});

`
  const values = rows
    .map(
      (r) =>
        `  (${sqlString(r.name)}, ${sqlString(r.description)}, ${sqlString(r.category)}, ${sqlString(r.version)}, ${sqlBool(r.enabled, true)}, ${sqlBool(r.installed, true)}, now(), now())`
    )
    .join(',\n')
  body = `${banner}${purge}insert into public.modules (
  name, description, category, version, enabled, installed, created_at, updated_at
)
values
${values}
on conflict (name) do update
set
  description = excluded.description,
  category = excluded.category,
  version = excluded.version,
  enabled = excluded.enabled,
  installed = excluded.installed,
  updated_at = now();
`
}

const header = `-- ! AUTO-GENERATED — source: each modules/<dir>/config.json (dir name = modules.name). Regenerate: pnpm supabase:merge-sql

`

writeFileSync(outFile, header + preamble + body, 'utf8')
process.stderr.write(
  `generate-seeder: ${rows.length} module(s) -> ${outFile}\n`
)
