create table if not exists public.modules (
  id bigint generated by default as identity primary key,
  name text not null,
  description text not null,
  category text not null,
  version text not null,
  enabled boolean not null default false,
  installed boolean not null default false,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

alter table public.modules add column if not exists name text;
alter table public.modules add column if not exists description text;
alter table public.modules add column if not exists category text;
alter table public.modules add column if not exists version text;
alter table public.modules add column if not exists enabled boolean not null default false;
alter table public.modules add column if not exists installed boolean not null default false;
alter table public.modules add column if not exists created_at timestamptz not null default now();
alter table public.modules add column if not exists updated_at timestamptz not null default now();

create unique index if not exists modules_name_unique_idx on public.modules (name);
alter table public.modules enable row level security;
drop policy if exists "modules_authenticated_all" on public.modules;
create policy "modules_authenticated_all" on public.modules for all to authenticated using (true) with check (true);
